# Copyright (c) 2025 Michał Alichniewicz
#
# This file is licensed under the MIT License.
# See the LICENSE file in the repository root for more information.
---
- hosts: switch-03
  gather_facts: False
  tasks:
    - name: gather facts (metro switch)
      local.dlink.metro_facts:
        gather_subset: "hardware"
      when: ansible_network_os == 'local.dlink.metro'
    - name: test smartsitch module (smart switch)
      local.dlink.smartswitch_hello:
      when: ansible_network_os == 'local.dlink.smartswitch'
      register: foo
    - name: gather facts (mikrotik router)
      community.routeros.facts:
        gather_subset: "hardware"
      when: ansible_network_os == 'routeros'
    - name: show foo
      debug:
        var: foo
      when: ansible_network_os == 'local.dlink.smartswitch'
    - name: show facts
      debug:
        var: ansible_facts
      when: ansible_network_os != 'local.dlink.smartswitch'