# Copyright (c) 2025 Michał Alichniewicz
#
# This file is licensed under the MIT License.
# See the LICENSE file in the repository root for more information.
---
- hosts: switch-01
  gather_facts: False
  tasks:
    - name: gather facts
      dlink.metro.facts:
        gather_subset: "config"
    - name: show facts
      debug:
        var: ansible_facts