# Copyright (c) 2025 Michał Alichniewicz
#
# This file is licensed under the MIT License.
# See the LICENSE file in the repository root for more information.
#
# SPDX-License-Identifier: MIT
---
 - name: install ca-certificates package
   apt:
     name: ca-certificates
     state: present
 - name: prepare keyring
   shell: install -m 0755 -d /etc/apt/keyrings
 - name: download Docker certificate
   get_url:
     url: https://download.docker.com/linux/ubuntu/gpg
     dest: /etc/apt/keyrings/docker.asc
     mode: a+r
 - name: setup apt repository
   apt_repository:
     repo: "deb [arch={{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
 - name: install Docker
   apt:
     pkg:
     - docker-ce 
     - docker-ce-cli 
     - containerd.io 
     - docker-buildx-plugin 
     - docker-compose-plugin
 - name: verify if Docker is installed
   docker_container:
     name: hello_world
     image: hello-world:latest
     state: started