# Copyright (c) 2025 Michał Alichniewicz
#
# This file is licensed under the MIT License.
# See the LICENSE file in the repository root for more information.

namespace: local
name: dlink
version: 0.0.1
readme: README.md
authors:
- Michał Alichniewicz <9162974+malichniewicz@users.noreply.github.com>
description: D-Link switches support
license:
- MIT
tags: [network, switch, d-link]
dependencies: {}
repository: https://github.com/malichniewicz/ansible-playbooks/tree/main/collections/ansible_collections/local/dlink
