# Copyright (c) 2025 Michał Alichniewicz
#
# This file is licensed under the MIT License.
# See the LICENSE file in the repository root for more information.
#
# SPDX-License-Identifier: MIT
---
platform: "linux"

dhcp-client:
  eno1:
    enabled: false
    interface: eno1
vlans:
  vlan-mgmt:
    id: 99
    interface: 
    - eno1
  vlan-user:
    id: 10
    interface: 
    - eno1
  vlan-iot:
    id: 50
    interface: 
    - eno1
