---
platform: "linux"

dhcp-client:
  eno1:
    enabled: false
    interface: eno1
vlans:
  vlan-mgmt:
    id: 99
    interface: 
    - eno1
  vlan-user:
    id: 10
    interface: 
    - eno1
  vlan-iot:
    id: 50
    interface: 
    - eno1
