# Copyright (c) 2025 Michał Alichniewicz
#
# This file is licensed under the MIT License.
# See the LICENSE file in the repository root for more information.
#
# SPDX-License-Identifier: MIT

# Usage:
# - role: setup_docker
#   container_name: container_name
#   workspace: workspace_path
#   compose_file: compose_file
#   dirs:
#    - directory_1
#    - directory_2
#   config_files:
#    - src: source_1
#      dest: dest_1
#    - src: source_2
#      dest: dest_2
#    - type: template

---
 - name: "{{ container_name }} // clear temporary flags for compose role"
   set_fact:
     config_changed: false
 - name: "{{ container_name }} // prepare workspace"
   file:
     path: "{{ workspace }}"
     state: directory
 - name: "{{ container_name }} // create additional directories"
   file:
     path: "{{ item }}"
   loop: "{{ dirs }}"
   register: additional_dirs
   when: additional_dirs is defined
 - name: "{{ container_name }} // deploy template config files"
   template:
     src: "{{ item.src }}"
     dest: "{{ item.dest }}"
   when: config_files is defined and (item.type is defined and item.type == "template")
   register: config_template_deployed
 - name: "{{ container_name }} // deploy config files"
   copy:
     src: "{{ item.src }}"
     dest: "{{ item.dest }}"
   loop: "{{ config_files }}"
   register: config_file_deployed
   when: config_files is defined and (item.type is not defined or item.type == "file")
 - name: "{{ container_name }} // deploy compose file"
   copy:
     src: "{{ compose_file }}"
     dest: "{{ (workspace, 'compose.yml') | path_join }}"
   when: compose_file is defined
 - name: "{{ container_name }} // deploy compose file template"
   template:
     src: "{{ compose_file_template }}"
     dest: "{{ (workspace, 'compose.yml') | path_join }}"
   when: compose_file_template is defined
 - name: "{{ container_name }} // run from compose file"
   community.docker.docker_compose_v2:
     project_src: "{{ workspace }}"
   register: container_running
 - name: "{{ container_name }} // restart if config changed"
   community.docker.docker_compose_v2:
     project_src: "{{ workspace }}" 
     state: restarted
   when: |
    config_files is defined and 
    (config_file_deployed.changed or config_template_deployed.changed) and 
    not container_running.changed and 
    not container_running.failed
   
