# Copyright (c) 2025 Michał Alichniewicz
#
# This file is licensed under the MIT License.
# See the LICENSE file in the repository root for more information.
#
# SPDX-License-Identifier: MIT
---
ansible_user: "{{ default.ansible_user }}"
ansible_ssh_public_key: "{{ lookup('file', 'files/ansible.pub' ) }}"
ansible_ssh_private_key_file: ~/.ssh/keys/ansible_access.key

management_network: 172.16.31.0/24

default:
  ansible_user: ansible

# Shared variables, to be used across multiple playbooks
exposed_docker_network: traefik
exposed_docker_network_subnet: 172.23.0.0/16